# Custom Language File for Launcher Customizer

[ejs.app]
title = "Fluorite client"

[ejs.landing]
mediaGitHubURL = "https://github.com/Zyntheor/Fluoriteclient"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@Zyntheor"
mediaDiscordURL = "https://discord.gg/zKdDTqN7KT"

[ejs.settings]
sourceGithubLink = "https://github.com/Zyntheor/Fluoriteclient"
supportLink = "https://github.com/Zyntheor/Fluoriteclient/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO FLUORITE"
welcomeDescription = "hi, you are in Fluorite client"
welcomeDescCTA = "You are just a few clicks away from Fluorite."
